name: deploy-page
run-name: ${{ github.actor }} merge
on:
  push:
    branches:
      - main
      - fix-tests
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: setup-git-credentials
        uses: de-vri-es/setup-git-credentials@v2.0.10
        with:
          credentials: ${{secrets.GIT_CREDENTIALS}}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm t
      - run: |
          git config --global user.email "cjlludwig@gmail.com"
          git config --global user.name "Connor Ludwig"
      - run: npm run deploy
